### PR TITLE
Create CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Manouchehri**
There's a lot of bug reports where people don't even mention what build they're running.

### CODE REVIEW

**Comment by benhillis** [comment]
This is a good suggestion, I will work with @russalex on getting this added.

**Comment by Chnkr** [comment]
I would strongly suggest using an issue template as well, see: https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by Manouchehri** [comment]
Was about to suggest that as well; wasn't sure how you guys would want it
formatted though.

**Comment by sundhaug92** [comment]
A few suggestions:
1. Indent the code-blocks in the example so that the numbering continues in the list
2. Add a point for "expected behaviour", especially if there exists links to documentation/specification for "the Linux way"
3. Change the text "the exact command" to "Steps required to reproduce", some bugs are not triggered by commands but rather by code written by the user themselves.
4. Link people to a [manual to write good bug-reports](https://musescore.org/en/developers-handbook/how-write-good-bug-report-step-step-instructions), to help people consider the how, why and whats of bug-reporting. 
5. Request that people tag their bugs so that it's easier to sort and filter through.

**Pull request merged**
